#ddev-generated
services:
  civicrm-cli-tools:
    container_name: ddev-${DDEV_SITENAME}-civicrm-cli-tools
    image: busybox:stable
    command: tail -f /dev/null
    restart: "no"
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    volumes:
      - ".:/mnt/ddev_config"
      - "ddev-global-cache:/mnt/ddev-global-cache"
